# render.yaml

services:
  - type: static_site
    name: my-html-website
    env: static
    static_publish_path: public
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
